name = "Filip B"
email = "filip.building.things@gmail.com"
sec_items = ["1.01Entry into a Material Definitive Agreement",
             "1.02Termination of a Material Definitive Agreement",
             "1.03Bankruptcy or Receivership",
             "1.04Mine Safety - Reporting of Shutdowns and Patterns of Violations",
             "2.01Completion of Acquisition or Disposition of Assets",
             "2.02Results of Operations and Financial Condition",
             "2.03Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant",
             "2.04Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement",
             "2.05Cost Associated with Exit or Disposal Activities",
             "2.06Material Impairments",
             "3.01Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing",
             "3.02Unregistered Sales of Equity Securities",
             "3.03Material Modifications to Rights of Security Holders",
             "4.01Changes in Registrant's Certifying Accountant",
             "4.02Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review",
             "5.01Changes in Control of Registrant",
             "5.02Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers Compensatory Arrangements of Certain Officers",
             "5.03Amendments to Articles of Incorporation or Bylaws; Change in Fiscal Year",
             "5.04Temporary Suspension of Trading Under Registrant's Employee Benefit Plans",
             "5.05Amendments to the Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics",
             "5.06Change in Shell Company Status",
             "5.07Submission of Matters to a Vote of Security Holders",
             "5.08Shareholder Nominations Pursuant to Exchange Act Rule 14a-11",
             "6.01ABS Informational and Computational Material",
             "6.02Change of Servicer or Trustee",
             "6.03Change in Credit Enhancement or Other External Support",
             "6.04Failure to Make a Required Distribution",
             "6.05Securities Act Updating Disclosure",
             "6.06Static Pool",
             "6.10Alternative Filings of Asset-Backed Issuers",
             "7.01Regulation FD Disclosure",
             "8.01Other Events",
             "9.01Financial Statements and Exhibits",
             "Signature"]

forms = ['8-K']

sec_items = {
    "1.01Entry into a Material Definitive Agreement": r"(\d+\.\d+)(Entry)(into)(a)(Material)(Definitive)(Agreement)",
    "1.02Termination of a Material Definitive Agreement": r"(\d+\.\d+)(Termination)(of)(a)(Material)(Definitive)(Agreement)",
    "1.03Bankruptcy or Receivership": r"(\d+\.\d+)(Bankruptcy)(or)(Receivership)",
    "1.04Mine Safety - Reporting of Shutdowns and Patterns of Violations": r"(\d+\.\d+)(Mine)(Safety)(-)(Reporting)(of)(Shutdowns)(and)(Patterns)(of)(Violations)",
    "2.01Completion of Acquisition or Disposition of Assets": r"(\d+\.\d+)(Completion)(of)(Acquisition)(or)(Disposition)(of)(Assets)",
    "2.02Results of Operations and Financial Condition": r"(\d+\.\d+)(Results)(of)(Operations)(and)(Financial)(Condition)",
    "2.03Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant": r"(\d+\.\d+)(Creation)(of)(a)(Direct)(Financial)(Obligation)(or)(an)(Obligation)(under)(an)(Off-Balance)(Sheet)(Arrangement)(of)(a)(Registrant)",
    "2.04Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement": r"(\d+\.\d+)(Triggering)(Events)(That)(Accelerate)(or)(Increase)(a)(Direct)(Financial)(Obligation)(or)(an)(Obligation)(under)(an)(Off-Balance)(Sheet)(Arrangement)",
    "2.05Cost Associated with Exit or Disposal Activities": r"(\d+\.\d+)(Cost)(Associated)(with)(Exit)(or)(Disposal)(Activities)",
    "2.06Material Impairments": r"(\d+\.\d+)(Material)(Impairments)",
    "3.01Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing": r"(\d+\.\d+)(Notice)(of)(Delisting)(or)(Failure)(to)(Satisfy)(a)(Continued)(Listing)(Rule)(or)(Standard;)(Transfer)(of)(Listing)",
    "3.02Unregistered Sales of Equity Securities": r"(\d+\.\d+)(Unregistered)(Sales)(of)(Equity)(Securities)",
    "3.03Material Modifications to Rights of Security Holders": r"(\d+\.\d+)(Material)(Modifications)(to)(Rights)(of)(Security)(Holders)",
    "4.01Changes in Registrant's Certifying Accountant": r"(\d+\.\d+)(Changes)(in)(Registrant's)(Certifying)(Accountant)",
    "4.02Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review": r"(\d+\.\d+)(Non-Reliance)(on)(Previously)(Issued)(Financial)(Statements)(or)(a)(Related)(Audit)(Report)(or)(Completed)(Interim)(Review)",
    "5.01Changes in Control of Registrant": r"(\d+\.\d+)(Changes)(in)(Control)(of)(Registrant)",
    "5.02Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers Compensatory Arrangements of Certain Officers": r"(\d+\.\d+)(Departure)(of)(Directors)(or)(Certain)(Officers;)(Election)(of)(Directors;)(Appointment)(of)(Certain)(Officers)(Compensatory)(Arrangements)(of)(Certain)(Officers)",
    "5.03Amendments to Articles of Incorporation or Bylaws; Change in Fiscal Year": r"(\d+\.\d+)(Amendments)(to)(Articles)(of)(Incorporation)(or)(Bylaws;)(Change)(in)(Fiscal)(Year)",
    "5.04Temporary Suspension of Trading Under Registrant's Employee Benefit Plans": r"(\d+\.\d+)(Temporary)(Suspension)(of)(Trading)(Under)(Registrant's)(Employee)(Benefit)(Plans)",
    "5.05Amendments to the Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics": r"(\d+\.\d+)(Amendments)(to)(the)(Registrant's)(Code)(of)(Ethics,)(or)(Waiver)(of)(a)(Provision)(of)(the)(Code)(of)(Ethics)",
    "5.06Change in Shell Company Status": r"(\d+\.\d+)(Change)(in)(Shell)(Company)(Status)",
    "5.07Submission of Matters to a Vote of Security Holders": r"(\d+\.\d+)(Submission)(of)(Matters)(to)(a)(Vote)(of)(Security)(Holders)",
    "5.08Shareholder Nominations Pursuant to Exchange Act Rule 14a-11": r"(\d+\.\d+)(Shareholder)(Nominations)(Pursuant)(to)(Exchange)(Act)(Rule)(14a-11)",
    "6.01ABS Informational and Computational Material": r"(\d+\.\d+)(ABS)(Informational)(and)(Computational)(Material)",
    "6.02Change of Servicer or Trustee": r"(\d+\.\d+)(Change)(of)(Servicer)(or)(Trustee)",
    "6.03Change in Credit Enhancement or Other External Support": r"(\d+\.\d+)(Change)(in)(Credit)(Enhancement)(or)(Other)(External)(Support)",
    "6.04Failure to Make a Required Distribution": r"(\d+\.\d+)(Failure)(to)(Make)(a)(Required)(Distribution)",
    "6.05Securities Act Updating Disclosure": r"(\d+\.\d+)(Securities)(Act)(Updating)(Disclosure)",
    "6.06Static Pool": r"(\d+\.\d+)(Static)(Pool)",
    "6.10Alternative Filings of Asset-Backed Issuers": r"(\d+\.\d+)(Alternative)(Filings)(of)(Asset-Backed)(Issuers)",
    "7.01Regulation FD Disclosure": r"(\d+\.\d+)(Regulation)(FD)(Disclosure)",
    "8.01Other Events": r"(\d+\.\d+)(Other)(Events)",
    "9.01Financial Statements and Exhibits": r"(\d+\.\d+)(Financial)(Statements)(and)(Exhibits)",
}

sec_items = {
    "1.01Entry into a Material Definitive Agreement": r"(1\.01)(Entry into a Material Definitive Agreement)",
    "1.02Termination of a Material Definitive Agreement": r"(1\.02)(Termination of a Material Definitive Agreement)",
    "1.03Bankruptcy or Receivership": r"(1\.03)(Bankruptcy or Receivership)",
    "1.04Mine Safety - Reporting of Shutdowns and Patterns of Violations": r"(1\.04)(Mine Safety - Reporting of Shutdowns and Patterns of Violations)",
    "2.01Completion of Acquisition or Disposition of Assets": r"(2\.01)(Completion of Acquisition or Disposition of Assets)",
    "2.02Results of Operations and Financial Condition": r"(2\.02)(Results of Operations and Financial Condition)",
    "2.03Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant": r"(2\.03)(Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant)",
    "2.04Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement": r"(2\.04)(Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement)",
    "2.05Cost Associated with Exit or Disposal Activities": r"(2\.05)(Cost Associated with Exit or Disposal Activities)",
    "2.06Material Impairments": r"(2\.06)(Material Impairments)",
    "3.01Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing": r"(3\.01)(Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing)",
    "3.02Unregistered Sales of Equity Securities": r"(3\.02)(Unregistered Sales of Equity Securities)",
    "3.03Material Modifications to Rights of Security Holders": r"(3\.03)(Material Modifications to Rights of Security Holders)",
    "4.01Changes in Registrant's Certifying Accountant": r"(4\.01)(Changes in Registrant's Certifying Accountant)",
    "4.02Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review": r"(4\.02)(Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review)",
    "5.01Changes in Control of Registrant": r"(5\.01)(Changes in Control of Registrant)",
    "5.02Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers Compensatory Arrangements of Certain Officers": r"(5\.02)(Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers Compensatory Arrangements of Certain Officers)",
    "5.03Amendments to Articles of Incorporation or Bylaws; Change in Fiscal Year": r"(5\.03)(Amendments to Articles of Incorporation or Bylaws; Change in Fiscal Year)",
    "5.04Temporary Suspension of Trading Under Registrant's Employee Benefit Plans": r"(5\.04)(Temporary Suspension of Trading Under Registrant's Employee Benefit Plans)",
    "5.05Amendments to the Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics": r"(5\.05)(Amendments to the Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics)",
    "5.06Change in Shell Company Status": r"(5\.06)(Change in Shell Company Status)",
    "5.07Submission of Matters to a Vote of Security Holders": r"(5\.07)(Submission of Matters to a Vote of Security Holders)",
    "5.08Shareholder Nominations Pursuant to Exchange Act Rule 14a-11": r"(5\.08)(Shareholder Nominations Pursuant to Exchange Act Rule 14a-11)",
    "6.01ABS Informational and Computational Material": r"(6\.01)(ABS Informational and Computational Material)",
    "6.02Change of Servicer or Trustee": r"(6\.02)(Change of Servicer or Trustee)",
    "6.03Change in Credit Enhancement or Other External Support": r"(6\.03)(Change in Credit Enhancement or Other External Support)",
    "6.04Failure to Make a Required Distribution": r"(6\.04)(Failure to Make a Required Distribution)",
    "6.05Securities Act Updating Disclosure": r"(6\.05)(Securities Act Updating Disclosure)",
    "6.06Static Pool": r"(6\.06)(Static Pool)",
    "6.10Alternative Filings of Asset-Backed Issuers": r"(6\.10)(Alternative Filings of Asset-Backed Issuers)",
    "7.01Regulation FD Disclosure": r"(7\.01)(Regulation FD Disclosure)",
    "8.01Other Events": r"(8\.01)(Other Events)",
    "9.01Financial Statements and Exhibits": r"(9\.01)(Financial Statements and Exhibits)",
    "Signatures": "Signatures"
}
