name = "Filip B"
email = "filip.building.things@gmail.com"
sec_items = ["1.01Entry into a Material Definitive Agreement",
"1.02Termination of a Material Definitive Agreement",
"1.03Bankruptcy or Receivership",
"1.04Mine Safety - Reporting of Shutdowns and Patterns of Violations",
"2.01Completion of Acquisition or Disposition of Assets",
"2.02Results of Operations and Financial Condition",
"2.03Creation of a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement of a Registrant",
"2.04Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement",
"2.05Cost Associated with Exit or Disposal Activities",
"2.06Material Impairments",
"3.01Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing",
"3.02Unregistered Sales of Equity Securities",
"3.03Material Modifications to Rights of Security Holders",
"4.01Changes in Registrant's Certifying Accountant",
"4.02Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review",
"5.01Changes in Control of Registrant",
"5.02Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers Compensatory Arrangements of Certain Officers",
"5.03Amendments to Articles of Incorporation or Bylaws; Change in Fiscal Year",
"5.04Temporary Suspension of Trading Under Registrant's Employee Benefit Plans",
"5.05Amendments to the Registrant's Code of Ethics, or Waiver of a Provision of the Code of Ethics",
"5.06Change in Shell Company Status",
"5.07Submission of Matters to a Vote of Security Holders",
"5.08Shareholder Nominations Pursuant to Exchange Act Rule 14a-11",
"6.01ABS Informational and Computational Material",
"6.02Change of Servicer or Trustee",
"6.03Change in Credit Enhancement or Other External Support",
"6.04Failure to Make a Required Distribution",
"6.05Securities Act Updating Disclosure",
"6.06Static Pool",
"6.10Alternative Filings of Asset-Backed Issuers",
"7.01Regulation FD Disclosure",
"8.01Other Events",
"9.01Financial Statements and Exhibits",
"Signature"]

forms = ['8-K']